## Kuryr configuration
openshift_use_kuryr: True
openshift_use_openshift_sdn: False
use_trunk_ports: True
os_sdn_network_plugin_name: cni
openshift_node_proxy_mode: userspace
kuryr_openstack_pool_driver: nested

# The value below needs to be set based on openshift_openstack_kuryr_pod_subnet_prefixlen based on tuning efforts.

openshift_kuryr_precreate_subports: false
kuryr_openstack_pool_batch: 3
kuryr_openstack_pool_max: 5
kuryr_openstack_pool_min: 1

#kuryr_openstack_ca: "/home/cloud-user/openshift/ca.crt.pem"

openshift_openstack_kuryr_controller_image: "registry.redhat.io/openshift3/kuryr-controller:{{ openshift_image_tag }}"
openshift_openstack_kuryr_cni_image: "registry.redhat.io/openshift3/kuryr-cni:{{ openshift_image_tag }}"

kuryr_openstack_public_net_id: 2ab2c523-ddc4-4488-bd53-b3a182dab504

# Adding metrics server to allow autoscaling

kuryr_openstack_global_namespaces: default,openshift-monitoring

# To disable namespace isolation, comment out the next 2 lines
openshift_kuryr_subnet_driver: namespace
openshift_kuryr_sg_driver: namespace

openshift_master_open_ports:
- service: dns tcp
  port: 53/tcp
- service: dns udp
  port: 53/udp

openshift_node_open_ports:
- service: dns tcp
  port: 53/tcp
- service: dns udp
  port: 53/udp

 
# Custom Settings:

# openshift_openstack_kuryr_service_subnet_cidr divided into two ranges
# Range 1: service netowrk (openshift_portal_net)
# Range 2: Amphora IP pool (openshift_openstack_kuryr_service_pool_start/end)
# The settings below mean the following:
# - Portal net (service IPs) will have 192.168.128.0-192.168.159.254
# - Amphora IPs will have 192.168.160.1-19.168.191.254
# - Pods will have  192.168.0.1-192.168.127.254

#SERVICE
openshift_portal_net: 192.168.128.0/19 # Ensure you don't have this defined elsewhere!
openshift_openstack_kuryr_service_subnet_cidr: 192.168.128.0/18
openshift_openstack_kuryr_service_pool_start: 192.168.160.1
openshift_openstack_kuryr_service_pool_end: 192.168.191.253

#POD
openshift_openstack_kuryr_pod_subnet_cidr: 192.168.0.0/17

# Pods per namespace determined by prefixlen (/24 = 256 pods per ns, /25 = 128 pods per ns, /26 = 64 pods per ns)

openshift_openstack_kuryr_pod_subnet_prefixlen: 26

openshift_openstack_node_secgroup_rules:

  # NOTE(shadower): the 53 rules are needed for Kuryr
  - direction: ingress
    protocol: tcp
    port_range_min: 53
    port_range_max: 53

  - direction: ingress
    protocol: udp
    port_range_min: 53
    port_range_max: 53

  - direction: ingress
    protocol: tcp
    port_range_min: 10250
    port_range_max: 10250
    remote_ip_prefix: "{{ openshift_openstack_kuryr_pod_subnet_cidr }}"

  - direction: ingress
    protocol: tcp
    port_range_min: 10250
    port_range_max: 10250
    remote_ip_prefix: "{{ openshift_openstack_subnet_cidr }}"

  - direction: ingress
    protocol: udp
    port_range_min: 4789
    port_range_max: 4789
    remote_ip_prefix: "{{ openshift_openstack_kuryr_pod_subnet_cidr }}"

  - direction: ingress
    protocol: udp
    port_range_min: 4789
    port_range_max: 4789
    remote_ip_prefix: "{{ openshift_openstack_subnet_cidr }}"

  - direction: ingress
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9100
    remote_ip_prefix: "{{ openshift_openstack_kuryr_pod_subnet_cidr }}"

  - direction: ingress
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9100
    remote_ip_prefix: "{{ openshift_openstack_subnet_cidr }}"

  - direction: ingress
    protocol: tcp
    port_range_min: 8444
    port_range_max: 8444
    remote_ip_prefix: "{{ openshift_openstack_kuryr_pod_subnet_cidr }}"

  - direction: ingress
    protocol: tcp
    port_range_min: 8444
    port_range_max: 8444
    remote_ip_prefix: "{{ openshift_openstack_subnet_cidr }}"

# End of Kuryr configuration
