---
- name: Enable the proper repositories for OpenShift installation
  hosts: nodes
  become: true
  tasks:
  - name: Register with activationkey and consume subscriptions matching Red Hat Cloud Suite or Red Hat OpenShift Container Platform
    redhat_subscription:
      state: present
      username: "{{ lookup('env','OREG_AUTH_USER') }}"
      password: "{{ lookup('env','OREG_AUTH_PASSWORD') }}"
      pool: 8a85f99b6b498682016b521dfe463949

  - name: Disable all current repositories
    rhsm_repository:
      name: '*'
      state: disabled

  - name: Enable Repositories
    rhsm_repository:
      name: "{{ item }}"
      state: enabled
    with_items:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ansible-2.6-rpms
      - rhel-7-server-ose-3.11-rpms

