---
# We need to specifc the etcd_ca_host as master-0
etcd_ca_host: "master-0.{{ openshift_openstack_full_dns_domain }}" 


openshift_deployment_type: openshift-enterprise
openshift_release: v3.11
openshift_minor_release: 3.11.452
#oreg_url: registry.access.redhat.com/openshift3/ose-${component}:${version}

oreg_auth_user: "{{ lookup('env','OREG_AUTH_USER') }}"
oreg_auth_password: "{{ lookup('env','OREG_AUTH_PASSWORD') }}"

openshift_image_tag: "v{{ openshift_minor_release }}"
openshift_pkg_version: "-{{ openshift_minor_release }}"

openshift_master_default_subdomain: apps.{{openshift_openstack_full_dns_domain}}
openshift_master_cluster_public_hostname: console.{{openshift_openstack_full_dns_domain}}

openshift_hosted_router_wait: True
openshift_hosted_registry_wait: True

### Authentication
 

openshift_master_identity_providers:

  - name: htpasswd_auth
    kind: HTPasswdPasswordIdentityProvider
    login: true
    challenge: true

# Password for both users is redhat 
openshift_master_htpasswd_users:

  admin: '$apr1$7sB5jHiw$9a0tdgSrsWPkTM9TpVZFk0'
  dev: '$apr1$7sB5jHiw$9a0tdgSrsWPkTM9TpVZFk0'

openshift_hostname_check: false

ansible_ssh_private_key_file: "/home/cloud-user/openshift/ocp-deploy.pem"


openshift_disable_check: "docker_image_availability"
openshift_examples_modify_imagestreams: true
oreg_test_login: false

osm_etcd_image: "registry.redhat.io/rhel7/etcd:3.2.28"



#OpenStack Credentials:
openshift_cloudprovider_kind: openstack
openshift_cloudprovider_openstack_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
openshift_cloudprovider_openstack_username: "{{ lookup('env','OS_USERNAME') }}"
openshift_cloudprovider_openstack_password: "{{ lookup('env','OS_PASSWORD') }}"
openshift_cloudprovider_openstack_tenant_name: "{{ lookup('env','OS_PROJECT_NAME') }}"
openshift_cloudprovider_openstack_blockstorage_version: v2
openshift_cloudprovider_openstack_domain_name: "{{ lookup('env','OS_USER_DOMAIN_NAME') }}"
#openshift_cloudprovider_openstack_conf_file: <path_to_local_openstack_configuration_file>

#Use Cinder volume for Openshift registry:
#openshift_hosted_registry_storage_kind: openstack
#openshift_hosted_registry_storage_access_modes: ['ReadWriteOnce']
#openshift_hosted_registry_storage_openstack_filesystem: xfs
#openshift_hosted_registry_storage_volume_size: 5Gi
#openshift_hosted_registry_storage_volume_name: registry
#openshift_hosted_registry_storage_annotations: ['volume.beta.kubernetes.io/storage-class: standard']

ansible_become: true

#Setting SDN (defaults to ovs-networkpolicy) not part of OSEv3.yml
#For more info, on which to choose, visit:
#https://docs.openshift.com/container-platform/3.11/architecture/networking/sdn.html#overview
#networkPluginName: redhat/ovs-networkpolicy
#networkPluginName: redhat/ovs-multitenant

#Configuring identity providers with Ansible
#For initial cluster installations, the Deny All identity provider is configured
#by default. It is recommended to be configured with either htpasswd
#authentication, LDAP authentication, or Allowing all authentication (not recommended)
#For more info, visit:
#https://docs.openshift.com/container-platform/3.10/install_config/configuring_authentication.html#identity-providers-ansible
#Example of Allowing All
#openshift_master_identity_providers: [{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]


#Optional Metrics (uncomment below lines for installation)

#openshift_metrics_install_metrics: true
#openshift_metrics_cassandra_storage_type: dynamic
#openshift_metrics_storage_volume_size: 25Gi
#openshift_metrics_cassandra_nodeselector: {"node-role.kubernetes.io/infra":"true"}
#openshift_metrics_hawkular_nodeselector: {"node-role.kubernetes.io/infra":"true"}
#openshift_metrics_heapster_nodeselector: {"node-role.kubernetes.io/infra":"true"}

#Optional Aggregated Logging (uncomment below lines for installation)

#openshift_logging_install_logging: true
#openshift_logging_es_pvc_dynamic: true
#openshift_logging_es_pvc_size: 30Gi
#openshift_logging_es_cluster_size: 3
#openshift_logging_es_number_of_replicas: 1
#openshift_logging_es_nodeselector: {"node-role.kubernetes.io/infra":"true"}
#openshift_logging_kibana_nodeselector: {"node-role.kubernetes.io/infra":"true"}
#openshift_logging_curator_nodeselector: {"node-role.kubernetes.io/infra":"true"}

openshift_service_catalog_remove: true
openshift_service_catalog_install: false
ansible_service_broker_remove: true
ansible_service_broker_install: false
template_service_broker_remove: true
template_service_broker_install: false
openshift_cluster_monitoring_operator_install: false

